# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: [push, pull_request]

name: unittests

jobs:
  unittests:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: "3.6.1", jaspRequiredFilesBranch: "Windows",        libPath: "R\\library"}
          - {os: macOS-latest,   r: "3.6.1", jaspRequiredFilesBranch: "MacOS-Original", libPath: "Frameworks/R.framework/Versions/3.6/Resources/library"}
          # - {os: ubuntu-20.04, r: "release", R_LIBS: "", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_UPGRADE: never
      VDIFFR_RUN_TESTS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Clone jasp-required-files
        run: |
          git clone --branch=${{ matrix.config.jaspRequiredFilesBranch }} https://github.com/jasp-stats/jasp-required-files.git "${GITHUB_WORKSPACE}/../pkgs"
        shell: bash

      - name: Setup .Rprofile
        run: |
          echo ".libPaths(c(file.path(Sys.getenv('GITHUB_WORKSPACE'), '..', 'pkgs', '${{ matrix.config.libPath }}'), .libPaths()))" >> ~/.Rprofile
          cat ~/.Rprofile

      - name: Locate JAGS (Windows)
        if: runner.os == 'Windows'
        run: echo "Sys.setenv(JAGS_HOME = file.path(Sys.getenv('GITHUB_WORKSPACE'), '..', 'pkgs', '64', 'JAGS'))"  >> ~/.Rprofile

      - name: Check libPaths
        run: |
          print(Sys.getenv())
          print(.libPaths())
          print(sapply(.libPaths(), dir))
        shell: Rscript {0}

      - name: Install xquartz & JAGS (macOS)
        if: runner.os == 'macOS'
        run: |
          # JAGS + xquartz
          rm '/usr/local/bin/gfortran'
          brew install jags
          brew cask install xquartz

      - name: Setup jaspTools
        run: |
          install.packages('remotes')
          remotes::install_github('jasp-stats/jaspTools')
          jaspTools::setupJaspTools()
        shell: Rscript {0}

      - name: Unit tests
        run: source("tests/testthat.R")
        shell: Rscript {0}
